import Icons from "@/Components/Icons/Icons";
import "@/styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";

export default function App({ Component, pageProps }: AppProps) {
  useEffect(() => {
    AOS.init({});
  }, []);

  return (
    <>
      <Head>
        <title>Coin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <AccountProvider> */}
      <Component {...pageProps} />
      <Icons />
      {/* </AccountProvider> */}
    </>
  );
}
